// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// createBedgraphCpp
String createBedgraphCpp(DataFrame sample_df, std::string type, std::string out_path, Nullable<String> group_name, Nullable<String> sample_name);
RcppExport SEXP _SMFnorm_createBedgraphCpp(SEXP sample_dfSEXP, SEXP typeSEXP, SEXP out_pathSEXP, SEXP group_nameSEXP, SEXP sample_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type sample_df(sample_dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type out_path(out_pathSEXP);
    Rcpp::traits::input_parameter< Nullable<String> >::type group_name(group_nameSEXP);
    Rcpp::traits::input_parameter< Nullable<String> >::type sample_name(sample_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(createBedgraphCpp(sample_df, type, out_path, group_name, sample_name));
    return rcpp_result_gen;
END_RCPP
}
// readMethylationFile
DataFrame readMethylationFile(std::string filename, int min_coverage);
RcppExport SEXP _SMFnorm_readMethylationFile(SEXP filenameSEXP, SEXP min_coverageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< int >::type min_coverage(min_coverageSEXP);
    rcpp_result_gen = Rcpp::wrap(readMethylationFile(filename, min_coverage));
    return rcpp_result_gen;
END_RCPP
}
// readMethylationFiles
List readMethylationFiles(CharacterVector filenames, int min_coverage);
RcppExport SEXP _SMFnorm_readMethylationFiles(SEXP filenamesSEXP, SEXP min_coverageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type filenames(filenamesSEXP);
    Rcpp::traits::input_parameter< int >::type min_coverage(min_coverageSEXP);
    rcpp_result_gen = Rcpp::wrap(readMethylationFiles(filenames, min_coverage));
    return rcpp_result_gen;
END_RCPP
}
// testCpp
std::string testCpp();
RcppExport SEXP _SMFnorm_testCpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(testCpp());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SMFnorm_createBedgraphCpp", (DL_FUNC) &_SMFnorm_createBedgraphCpp, 5},
    {"_SMFnorm_readMethylationFile", (DL_FUNC) &_SMFnorm_readMethylationFile, 2},
    {"_SMFnorm_readMethylationFiles", (DL_FUNC) &_SMFnorm_readMethylationFiles, 2},
    {"_SMFnorm_testCpp", (DL_FUNC) &_SMFnorm_testCpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_SMFnorm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
