# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createBedgraphCpp <- function(sample_df, type, out_path, group_name = NULL, sample_name = NULL) {
    .Call(`_SMFnorm_createBedgraphCpp`, sample_df, type, out_path, group_name, sample_name)
}

readMethylationFile <- function(filename) {
    .Call(`_SMFnorm_readMethylationFile`, filename)
}

readMethylationFiles <- function(filenames) {
    .Call(`_SMFnorm_readMethylationFiles`, filenames)
}

testCpp <- function() {
    .Call(`_SMFnorm_testCpp`)
}

